---
# 🟢 PARTIE EXTRACT

### Ex E1 ⭐ — Explorer les sources
Affichez pour chaque DataFrame : shape, colonnes, dtypes, et les 3 premières lignes.

In [1]:
import pandas as pd
df_clients = pd.read_csv(r'C:\Users\eraze\Downloads\ETL\data\clients.csv')
df_commandes1 = pd.read_csv(r'C:\Users\eraze\Downloads\ETL\data\commandes_Q1.csv')
df_commandes2 = pd.read_csv(r'C:\Users\eraze\Downloads\ETL\data\commandes_Q2.csv')
df_produits = pd.read_csv(r'C:\Users\eraze\Downloads\ETL\data\produits.csv')

In [2]:
# creation de la variable avec les données 
my_data = [df_clients, df_commandes1, df_commandes2, df_produits]

for df in my_data:
    print("Shape :", df.shape)
    print("Colonnes :", df.columns.tolist())
    print("Types :\n", df.dtypes)
    display(df.head(3)) 
    print()

Shape : (515, 9)
Colonnes : ['client_id', 'nom', 'email', 'ville', 'region', 'segment', 'date_inscription', 'ca_historique', 'actif']
Types :
 client_id               str
nom                     str
email                   str
ville                   str
region                  str
segment                 str
date_inscription        str
ca_historique       float64
actif                  bool
dtype: object

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
2,CLI0003,Client_3,client3@email.fr,Nantes,Occitanie,PME,2023-11-17,6895.77,True

Shape : (3020, 10)
Colonnes : ['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire', 'montant_total', 'date_commande', 'statut', 'mode_paiement', 'region_livraison']
Types :
 commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
mode_paiement           str
region_livraison        str
dtype: object

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine

Shape : (3220, 11)
Colonnes : ['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire', 'montant_total', 'date_commande', 'statut', 'moyen_paiement', 'region_livraison', 'devise']
Types :
 commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
moyen_paiement          str
region_livraison        str
devise                  str
dtype: object

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,moyen_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR
2,CMD-Q2-00003,CLI0282,PRD0021,8,78.18,625.44,2024-05-05,annulée,CB,Occitanie,EUR

Shape : (152, 7)
Colonnes : ['produit_id', 'nom', 'categorie', 'prix_unitaire', 'stock', 'fournisseur', 'actif']
Types :
 produit_id           str
nom                  str
categorie            str
prix_unitaire    float64
stock              int64
fournisseur          str
actif               bool
dtype: object

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
2,PRD0003,Produit_Inf_3,Informatique,83.45,372,ElecPlus,False

### Ex E2 ⭐ — Détecter les différences entre Q1 et Q2
Trouvez les colonnes présentes dans Q2 mais absentes de Q1, et vice-versa.
Affichez les différences clairement.

In [3]:
# chercher les colonnes de C1 qui ne sont pas dans C2
diff_c1 = df_commandes1.columns[~df_commandes1.columns.isin(df_commandes2.columns)]
# chercher les colonnes de C2 absentes de C1
diff_c2 = df_commandes2.columns[~df_commandes2.columns.isin(df_commandes1.columns)]
# affichage des résultats 
print("Colonnes uniquement dans C1 :", diff_c1.tolist())
print("Colonnes uniquement dans C2 :", diff_c2.tolist())

Colonnes uniquement dans C1 : ['mode_paiement']
Colonnes uniquement dans C2 : ['moyen_paiement', 'devise']

### Ex E3 ⭐ — Harmoniser les colonnes
1. Renommez la colonne problématique dans Q2 pour qu'elle corresponde à Q1
2. Ajoutez la colonne manquante dans Q1 avec une valeur par défaut
3. Vérifiez que les deux DataFrames ont maintenant les mêmes colonnes

In [4]:
# on renomme la colonne C2
df = df_commandes2.rename(columns={'moyen_paiement':'mode_paiement'})
print(df)
# on ajoute la colonne manquante 
df_commandes1['devise']= "EUR"
print(df_commandes1)
# vérification des correspondances 
verif = df_commandes1.columns.equals(df_commandes2.columns)
print(f"les 2 colonnes sont identiques ")

       commande_id client_id produit_id  quantite  prix_unitaire  \
0     CMD-Q2-00001   CLI0122    PRD0041         5          48.15
1     CMD-Q2-00002   CLI0346    PRD0106         1          52.42
2     CMD-Q2-00003   CLI0282    PRD0021         8          78.18
3     CMD-Q2-00004   CLI0292    PRD0141         9         326.57
4     CMD-Q2-00005   CLI0392    PRD0054         5         124.37
...            ...       ...        ...       ...            ...
3215  CMD-Q2-00605   CLI0341    PRD0095         8         106.83
3216  CMD-Q2-02643   CLI0493    PRD0076         9         211.08
3217  CMD-Q2-00511   CLI0428    PRD0081         6          49.36
3218  CMD-Q2-02836   CLI0085    PRD0126         1          82.76
3219  CMD-Q2-03170   CLI0122    PRD0120         5         107.93

      montant_total date_commande     statut mode_paiement  \
0            240.75    2024-05-14  retournée            CB
1             52.42    2024-04-18     livrée            CB
2            625.44    2024-05-05    annulée            CB
3           2939.13    2024-05-31     livrée        Chèque
4            621.85    2024-06-27     livrée            CB
...             ...           ...        ...           ...
3215         854.64    2024-05-02  retournée            CB
3216        1899.72    2024-06-19   en_cours            CB
3217         296.16    2024-04-05     livrée            CB
3218          82.76    2024-05-14     livrée            CB
3219         539.65    2024-04-02     livrée        PayPal

        region_livraison devise
0            Auvergne-RA    EUR
1                   PACA    EUR
2              Occitanie    EUR
3              Occitanie    EUR
4            Auvergne-RA    EUR
...                  ...    ...
3215       Île-de-France    EUR
3216           Occitanie    EUR
3217           Occitanie    EUR
3218           Occitanie    EUR
3219  Nouvelle-Aquitaine    EUR

[3220 rows x 11 columns]
       commande_id client_id produit_id  quantite  prix_unitaire  \
0     CMD-Q1-00001   CLI0496    PRD0081         1          49.36
1     CMD-Q1-00002   CLI0305    PRD0058         5         118.62
2     CMD-Q1-00003   CLI0044    PRD0128         7          99.94
3     CMD-Q1-00004   CLI0381    PRD0061         8          75.83
4     CMD-Q1-00005   CLI0187    PRD0040         4          71.91
...            ...       ...        ...       ...            ...
3015  CMD-Q1-02619   CLI0400    PRD0066         7         181.07
3016  CMD-Q1-01687   CLI0071    PRD0097         6         149.62
3017  CMD-Q1-01222   CLI0324    PRD0102         8          23.26
3018  CMD-Q1-02488   CLI0093    PRD0036         3         211.79
3019  CMD-Q1-01522   CLI0275    PRD0024         6          20.71

      montant_total date_commande    statut mode_paiement    region_livraison  \
0             49.36    2024-03-18   annulée            CB           Occitanie
1            593.10    2024-01-23    livrée            CB           Occitanie
2            699.58    2024-01-15    livrée        PayPal  Nouvelle-Aquitaine
3            606.64    2024-01-17   annulée        PayPal                PACA
4            287.64    2024-03-20  en_cours            CB           Occitanie
...             ...           ...       ...           ...                 ...
3015        1267.49    2024-03-14    livrée      Virement  Nouvelle-Aquitaine
3016         897.72    2024/02/16    livrée            CB         Auvergne-RA
3017         186.08    2024-02-06    livrée            CB           Occitanie
3018         635.37    2024-02-18    livrée            CB  Nouvelle-Aquitaine
3019         124.26    2024-02-15    livrée        PayPal       Île-de-France

     devise
0       EUR
1       EUR
2       EUR
3       EUR
4       EUR
...     ...
3015    EUR
3016    EUR
3017    EUR
3018    EUR
3019    EUR

[3020 rows x 11 columns]
les 2 colonnes sont identiques

### Ex E4 ⭐ — Consolider avec pd.concat
1. Ajoutez une colonne `source` dans Q1 (`'Q1_2024'`) et Q2 (`'Q2_2024'`)
2. Concaténez Q1 et Q2 avec `pd.concat`
3. Vérifiez que le total de lignes est cohérent
4. Affichez la répartition des lignes par source

In [5]:
# ajout colonne source dans Q1 et Q2
df_commandes1['source'] = 'Q1_2024'
df_commandes2['source'] = 'Q2_2024'
df_commandes1

# concatenation de Q1 et Q2 
df_commandes = pd.concat([df_commandes1, df_commandes2])
(df_commandes)

# verification de la cohérence des lignes 
total_attendu = df_commandes1.shape[0] + df_commandes2.shape[0]
print(f"Le compte est bon ? {df_commandes.shape[0] == total_attendu}")

# affichage de la répartition des lignes 
display(df_commandes['source'].value_counts())

Le compte est bon ? True

source
Q2_2024    3220
Q1_2024    3020
Name: count, dtype: int64

### Ex E5 ⭐⭐ — Fonction extract()
Encapsulez tout dans une fonction `extract(q1_path, q2_path, clients_path, produits_path) -> dict`
qui retourne un dictionnaire avec les 4 DataFrames harmonisés et consolidés.
La fonction doit afficher des logs à chaque étape.

In [6]:
# etape1 création de la fonction extract avec ses différents paramètres puis chargement des fichiers
def extract(q1_path, q2_path, clients_path, produits_path):
    print("Chargement des fichiers")
    df_commandes1 = pd.read_csv(q1_path)
    df_commandes2 = pd.read_csv(q2_path)
    df_clients = pd.read_csv(clients_path)
    df_produits = pd.read_csv(produits_path)
    print("Chargement des fichiers terminés")

    # etape 2 ) harmonisation des données pour s'assurer que les 2 tableaux ont la meme struture
    print("harmonisation des données ")
    # les 2 tableaux seront similaires
    df_commandes2 = df_commandes2.rename(columns={'moyen_paiement': 'mode_paiement'})
    # ajout de la colonne devise manquante sur le tableau 1
    df_commandes1['devise'] = 0

    # etape 3 ) concaténation ou consolidation
    print("consolidation en cours ")
    df_commandes1['source'] = 'Q1_2024'
    df_commandes2['source'] = 'Q2_2024'

    # fusion de 2 tableaux avec concat et ignore index pour avoir une numeration logique de l'index
    df_commandes = pd.concat([df_commandes1, df_commandes2], ignore_index=True)

    # création du dictionnaire
    print("création du dictionnaire")
    resultats = {
        'commandes' : df_commandes,
        'clients' : df_clients,
        'produits' : df_produits
    }
    
    print("Extraction effectuée avec succès")
    return resultats

#  execution du code
# chemin opérationnel
chemin_q1 = r'C:\Users\eraze\Downloads\ETL\data\commandes_Q1.csv'
chemin_q2 = r'C:\Users\eraze\Downloads\ETL\data\commandes_Q2.csv'
chemin_clients = r'C:\Users\eraze\Downloads\ETL\data\clients.csv'
chemin_produits = r'C:\Users\eraze\Downloads\ETL\data\produits.csv'

# On appelle la fonction et on stocke le résultat
mes_donnees = extract(chemin_q1, chemin_q2, chemin_clients, chemin_produits)

# affichage des résultats 
print("Aperçu des commandes")
display(mes_donnees['commandes'].head(5))

print("aperçu des clients")
display(mes_donnees['clients'].head(5))

print("aperçu des produits")
display(mes_donnees['produits'].head(5))

Chargement des fichiers
Chargement des fichiers terminés
harmonisation des données
consolidation en cours
création du dictionnaire
Extraction effectuée avec succès
Aperçu des commandes

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,0,Q1_2024
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,0,Q1_2024
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,0,Q1_2024
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,0,Q1_2024
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,0,Q1_2024

aperçu des clients

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
2,CLI0003,Client_3,client3@email.fr,Nantes,Occitanie,PME,2023-11-17,6895.77,True
3,CLI0004,Client_4,client4@email.fr,Nantes,PACA,Particulier,2023-10-20,11034.84,True
4,CLI0005,Client_5,client5@email.fr,Paris,Île-de-France,Particulier,2022-12-29,2331.35,False

aperçu des produits

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
2,PRD0003,Produit_Inf_3,Informatique,83.45,372,ElecPlus,False
3,PRD0004,Produit_Inf_4,Informatique,42.82,151,DataStore,True
4,PRD0005,Produit_Inf_5,Informatique,95.95,413,MediaShop,True

---
# 🟡 PARTIE TRANSFORM

### Ex T1 ⭐ — Audit initial
Écris une fonction `audit_dataframe(df, nom)` qui affiche :
- Shape
- Nombre de NaN total et par colonne (en %)
- Nombre de doublons
- Types de chaque colonne

In [7]:
# definition de la fonction demandée 

def audit_dataframe(df, nom):
    # affichage du nombre de colonnes et de lignes
    display(df.shape)
    
    # affichage du nombre de NaN total
    total_nan = df.isna().sum().sum()
    print(f"\n Nombre TOTAL de cases vides (NaN) : {total_nan}")
    
    # affichage du pourcentage de nan par colonne
    pourcentage_colonne = (df.isna().mean() * 100).round(2)
    display(pourcentage_colonne)
    
    # affichage des doublons
    print("\n Nombre de doublons :", df.duplicated().sum())
    
    # affichage du type de chaque colonne
    print("\n Types de données par colonne :")
    display(df.dtypes)
    

# appel de la fonction pour affichage des données 
audit_dataframe(mes_donnees['commandes'], "Tableau des Commandes")

(6240, 12)

 Nombre TOTAL de cases vides (NaN) : 179

commande_id         0.00
client_id           0.00
produit_id          0.00
quantite            0.00
prix_unitaire       0.00
montant_total       1.88
date_commande       0.00
statut              0.99
mode_paiement       0.00
region_livraison    0.00
devise              0.00
source              0.00
dtype: float64

 Nombre de doublons : 40

 Types de données par colonne :

commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
mode_paiement           str
region_livraison        str
devise               object
source                  str
dtype: object

### Ex T2 ⭐ — Supprimer les doublons
Sur le DataFrame consolidé :
1. Détectez et affichez le nombre de doublons
2. Montrez 3 exemples de lignes dupliquées
3. Supprimez les doublons (gardez la première occurrence)
4. Vérifiez qu'il n'en reste plus

In [8]:
# on note notre tableau
df_commandes = mes_donnees['commandes']

# affichage des doublons 
nbr_doublons = df_commandes.duplicated().sum()
print(f"\n Nombre de doublons : {nbr_doublons}")

# exemple de lignes dupliquées
display(df_commandes[df_commandes.duplicated()].head(3))
# # Affiche uniquement les lignes qui sont des doublons
# doublons = df_commandes[df_commandes.duplicated(keep=False)]

# # Tri des résultats pour mettre les doublons côte à côte
# display(doublons.sort_values(by=list(df_commandes.columns)))

# suppression de doublons 
df_commandes.drop_duplicates(keep = 'first', inplace=True)

print("nombre de doublons après suppression :",df_commandes.duplicated().sum())

 Nombre de doublons : 40

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
3000,CMD-Q1-02950,CLI0271,PRD0124,2,55.52,111.04,2024-02-27,annulée,CB,Île-de-France,0,Q1_2024
3001,CMD-Q1-00072,CLI0001,PRD0027,7,45.84,320.88,2024-03-20,en_cours,CB,Île-de-France,0,Q1_2024
3002,CMD-Q1-00145,CLI0441,PRD0020,9,304.72,2742.48,2024-02-19,livrée,CB,Île-de-France,0,Q1_2024

nombre de doublons après suppression : 0

### Ex T3 ⭐ — Corriger les types
1. Convertissez `date_commande` en datetime en gérant les formats incohérents
2. Extrayez : `annee`, `mois`, `trimestre`, `jour_semaine`
3. Convertissez `quantite` en numérique avec gestion des erreurs
4. Affichez les types avant et après

In [9]:
# affichage des types 
display(df_commandes.dtypes)

# conversion de la date de commande avec gestion des incohérences 
df_commandes['date_commande']= pd.to_datetime(df_commandes['date_commande'],format='mixed', dayfirst=True, errors='coerce')

# extraction de l'année, mois,trimestre,jour_semaine
df_commandes["année"] = df_commandes['date_commande'].dt.year
df_commandes["mois"] = df_commandes['date_commande'].dt.month
df_commandes["trimestre"] = df_commandes['date_commande'].dt.quarter
df_commandes["jour_semaine"] = df_commandes['date_commande'].dt.day_name
(df_commandes)

# conversion de quantité en numérique :oblige l'ordinateur à lire les valeurs comme des nombres 
df_commandes['quantite'] = pd.to_numeric(df_commandes['quantite'], errors = 'coerce')
(df_commandes)

# affichage des types après toutes les modifications 
display(df_commandes.dtypes)

commande_id             str
client_id               str
produit_id              str
quantite              int64
prix_unitaire       float64
montant_total       float64
date_commande           str
statut                  str
mode_paiement           str
region_livraison        str
devise               object
source                  str
dtype: object

commande_id                    str
client_id                      str
produit_id                     str
quantite                     int64
prix_unitaire              float64
montant_total              float64
date_commande       datetime64[us]
statut                         str
mode_paiement                  str
region_livraison               str
devise                      object
source                         str
année                        int32
mois                         int32
trimestre                    int32
jour_semaine                object
dtype: object

### Ex T4 ⭐⭐ — Traiter les NaN
Pour chaque colonne avec des NaN, choisissez et appliquez la stratégie adaptée :
- `montant_total` NaN → recalculer depuis `quantite × prix_unitaire`
- `statut` NaN → valeur par défaut `'inconnu'`
- `date_commande` NaT → supprimer la ligne (donnée critique)

Justifiez chaque choix dans un commentaire.

In [10]:
# calcul du montant total NaN
df_commandes['montant_total'] = df_commandes['montant_total'].fillna(df_commandes['quantite'] * df_commandes['prix_unitaire'])
df_commandes

# statut des NaN avec valeur par défaut inconnu
df_commandes['statut'] = df_commandes['statut'].fillna('inconnu')
df_commandes 

# suppression de la ligne 
df_commandes.dropna(subset=['date_commande'], inplace=True)

print("Nombre de NaN restants par colonne :")
print(df_commandes['date_commande'].isna().sum())

Nombre de NaN restants par colonne :
0

### Ex T5 ⭐⭐ — Détecter et traiter les aberrants
1. Détectez les prix négatifs → supprimez ces lignes
2. Détectez les quantités nulles ou négatives → supprimez
3. Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
4. Affichez un résumé des corrections effectuées

In [11]:
# affichage compteur de ligne avant correction
lignes_av = df_commandes.shape[0]
print(lignes_av)

# détection et suppression des prix négatifs
df_commandes = df_commandes[df_commandes["prix_unitaire"] >= 0]
display(df_commandes)

# # détection et suppression des quantité négatives
df_commandes = df_commandes[df_commandes["quantite"] > 0]
print(df_commandes)

# vérification de la cohérence du montant total
df_commandes['montant_total'] = df_commandes['quantite'] * df_commandes['prix_unitaire']
df_commandes

# résumé des des corrections effectuées
lignes_ap = df_commandes.shape[0]
lignes_supp = lignes_av - lignes_ap

print(f"Lignes aberrantes supprimées : {lignes_supp}")
print("Les montants totaux ont été recalculés.")

6200

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source,année,mois,trimestre,jour_semaine
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,0,Q1_2024,2024,3,1,<bound method DatetimeArray.day_name of <panda...
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,0,Q1_2024,2024,1,1,<bound method DatetimeArray.day_name of <panda...
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,0,Q1_2024,2024,1,1,<bound method DatetimeArray.day_name of <panda...
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,0,Q1_2024,2024,1,1,<bound method DatetimeArray.day_name of <panda...
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,0,Q1_2024,2024,3,1,<bound method DatetimeArray.day_name of <panda...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6215,CMD-Q2-03196,CLI0454,PRD0127,1,63.31,63.31,2024-09-06,livrée,PayPal,Auvergne-RA,EUR,Q2_2024,2024,9,3,<bound method DatetimeArray.day_name of <panda...
6216,CMD-Q2-03197,CLI0222,PRD0054,5,124.37,621.85,2024-10-06,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q2_2024,2024,10,4,<bound method DatetimeArray.day_name of <panda...
6217,CMD-Q2-03198,CLI0030,PRD0135,3,112.71,338.13,2024-06-05,livrée,CB,Nouvelle-Aquitaine,EUR,Q2_2024,2024,6,2,<bound method DatetimeArray.day_name of <panda...
6218,CMD-Q2-03199,CLI0187,PRD0091,7,75.28,526.96,2024-05-21,livrée,CB,Nouvelle-Aquitaine,EUR,Q2_2024,2024,5,2,<bound method DatetimeArray.day_name of <panda...
6219,CMD-Q2-03200,CLI0434,PRD0059,8,117.97,943.76,2024-06-25,livrée,CB,PACA,EUR,Q2_2024,2024,6,2,<bound method DatetimeArray.day_name of <panda...

       commande_id client_id produit_id  quantite  prix_unitaire  \
0     CMD-Q1-00001   CLI0496    PRD0081         1          49.36
1     CMD-Q1-00002   CLI0305    PRD0058         5         118.62
2     CMD-Q1-00003   CLI0044    PRD0128         7          99.94
3     CMD-Q1-00004   CLI0381    PRD0061         8          75.83
4     CMD-Q1-00005   CLI0187    PRD0040         4          71.91
...            ...       ...        ...       ...            ...
6215  CMD-Q2-03196   CLI0454    PRD0127         1          63.31
6216  CMD-Q2-03197   CLI0222    PRD0054         5         124.37
6217  CMD-Q2-03198   CLI0030    PRD0135         3         112.71
6218  CMD-Q2-03199   CLI0187    PRD0091         7          75.28
6219  CMD-Q2-03200   CLI0434    PRD0059         8         117.97

      montant_total date_commande    statut mode_paiement    region_livraison  \
0             49.36    2024-03-18   annulée            CB           Occitanie
1            593.10    2024-01-23    livrée            CB           Occitanie
2            699.58    2024-01-15    livrée        PayPal  Nouvelle-Aquitaine
3            606.64    2024-01-17   annulée        PayPal                PACA
4            287.64    2024-03-20  en_cours            CB           Occitanie
...             ...           ...       ...           ...                 ...
6215          63.31    2024-09-06    livrée        PayPal         Auvergne-RA
6216         621.85    2024-10-06    livrée        PayPal  Nouvelle-Aquitaine
6217         338.13    2024-06-05    livrée            CB  Nouvelle-Aquitaine
6218         526.96    2024-05-21    livrée            CB  Nouvelle-Aquitaine
6219         943.76    2024-06-25    livrée            CB                PACA

     devise   source  année  mois  trimestre  \
0         0  Q1_2024   2024     3          1
1         0  Q1_2024   2024     1          1
2         0  Q1_2024   2024     1          1
3         0  Q1_2024   2024     1          1
4         0  Q1_2024   2024     3          1
...     ...      ...    ...   ...        ...
6215    EUR  Q2_2024   2024     9          3
6216    EUR  Q2_2024   2024    10          4
6217    EUR  Q2_2024   2024     6          2
6218    EUR  Q2_2024   2024     5          2
6219    EUR  Q2_2024   2024     6          2

                                           jour_semaine
0     <bound method DatetimeArray.day_name of <panda...
1     <bound method DatetimeArray.day_name of <panda...
2     <bound method DatetimeArray.day_name of <panda...
3     <bound method DatetimeArray.day_name of <panda...
4     <bound method DatetimeArray.day_name of <panda...
...                                                 ...
6215  <bound method DatetimeArray.day_name of <panda...
6216  <bound method DatetimeArray.day_name of <panda...
6217  <bound method DatetimeArray.day_name of <panda...
6218  <bound method DatetimeArray.day_name of <panda...
6219  <bound method DatetimeArray.day_name of <panda...

[6149 rows x 16 columns]
Lignes aberrantes supprimées : 51
Les montants totaux ont été recalculés.

### Ex T6 ⭐⭐ — Jointures avec les référentiels
1. Nettoyez `df_clients` (doublons sur `client_id`)
2. Filtrez `df_produits` pour ne garder que les produits actifs
3. Faites un LEFT JOIN commandes ← clients (colonnes : ville, region, segment)
4. Faites un LEFT JOIN commandes ← produits (colonnes : nom, categorie, fournisseur)
5. Vérifiez le nombre de lignes avant et après (doit être identique avec LEFT JOIN)

In [29]:
# suppression des doublons 
df_clients.drop_duplicates(subset=['client_id'], inplace = True)

# filtrage df_produits pour ne garder que les actifs
df_produits = df_produits[df_produits['actif'] == True]
# df_produits

# verification nombre de lignes avant modification
lignes_av = df_commandes.shape[0]

# jointure avec les clients 
df_commandes = df_commandes.merge(
    df_clients[['client_id', 'ville', 'region', 'segment','date_inscription']], 
    on='client_id', 
    how='left'
)

# jointure avec les produits 
# jointure avec les produits
df_commandes = df_commandes.merge(
    df_produits[['produit_id', 'nom', 'categorie', 'fournisseur']], 
    on='produit_id', 
    how='left'
)

# verification du nombre de lignes après 
lignes_ap = df_commandes.shape[0]
print(f"nombres lignes avant :{lignes_av}")
print(f"nombres lignes apres :{lignes_ap}")

nombres lignes avant :6149
nombres lignes apres :6149

### Ex T7 ⭐⭐ — Feature Engineering
Créez les colonnes suivantes :
1. `tranche_montant` : `<100€` / `100-500€` / `500-2000€` / `>2000€` avec `pd.cut()`
2. `saison` : depuis le mois (Hiver/Printemps/Été/Automne)
3. `est_annulee` : booléen True si statut == 'annulée'
4. `ca_perdu` : montant_total si commande annulée, sinon 0
5. `delai_inscription_commande` : nb de jours entre date_inscription du client et date_commande

Affichez `value_counts()` pour les colonnes catégorielles créées.

In [32]:
# création des limites de pd.cut
bins = [0,100,500,2000,float('inf')]
# création des labels de pd.cut
labels = ['<100€', '100-500€','500-2000€','>2000€']

# création de la colonne tranche_montant avec pd cut 
df_commandes['tranche_montant'] = pd.cut(df_commandes['montant_total'],bins = bins , labels = labels )

# création de la fonction pour les saisons et de la colonne saison
def saisons(mois):
    if mois in [12,1,2]:
        return 'hiver'
    elif mois in [3,4,5]:
        return 'printemps'
    elif mois in [6,7,8]:
        return 'été'
    else:
        return 'automne'

df_commandes['saison'] = df_commandes['date_commande'].dt.month.apply(saisons)

# création de la colonne est_annulee
df_commandes['est_annulee'] = df_commandes['statut'] == 'annulée'

# création de la colonne ca_perdu
df_commandes['ca_perdu'] = 0.0
df_commandes.loc[df_commandes['est_annulee'] == True , 'ca_perdu'] = df_commandes['montant_total']
# df_commandes

# création de la colonne delai 
# 1. On force Pandas à lire ces deux colonnes comme de vraies dates mathématiques
df_commandes['date_commande'] = pd.to_datetime(df_commandes['date_commande'])
df_commandes['date_inscription'] = pd.to_datetime(df_commandes['date_inscription'])

# 2. Maintenant que ce sont deux vraies dates, la soustraction va fonctionner !
df_commandes['delai_inscription_commande'] = (df_commandes['date_commande'] - df_commandes['date_inscription']).dt.days

# Affichage pour vérifier le résultat
display(df_commandes)


# affichage des values_counts
print(df_commandes['tranche_montant'].value_counts())
print(df_commandes['saison'].value_counts())
print(df_commandes['est_annulee'].value_counts())

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,...,est_annulee,ca_perdu,ville_y,region_y,segment_y,date_inscription,nom_y,categorie_y,fournisseur_y,delai_inscription_commande
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,...,True,49.36,Marseille,PACA,Particulier,2021-07-26,NaN,NaN,NaN,966.0
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,...,False,0.00,Nantes,Nouvelle-Aquitaine,Startup,2023-03-31,Produit_Aud_58,Audio,TechPro,298.0
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,...,False,0.00,Nantes,PACA,Particulier,2020-07-12,NaN,NaN,NaN,1282.0
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,...,True,606.64,Lyon,Auvergne-RA,Particulier,2023-01-07,Produit_Aud_61,Audio,DataStore,375.0
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,...,False,0.00,Montpellier,Île-de-France,Particulier,2020-10-24,NaN,NaN,NaN,1243.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6144,CMD-Q2-03196,CLI0454,PRD0127,1,63.31,63.31,2024-09-06,livrée,PayPal,Auvergne-RA,...,False,0.00,Paris,Auvergne-RA,Startup,2020-08-29,Produit_Rés_127,Réseau,MediaShop,1469.0
6145,CMD-Q2-03197,CLI0222,PRD0054,5,124.37,621.85,2024-10-06,livrée,PayPal,Nouvelle-Aquitaine,...,False,0.00,Toulouse,Nouvelle-Aquitaine,PME,2021-09-20,Produit_Tél_54,Téléphonie,TechPro,1112.0
6146,CMD-Q2-03198,CLI0030,PRD0135,3,112.71,338.13,2024-06-05,livrée,CB,Nouvelle-Aquitaine,...,False,0.00,Nice,PACA,Grand Compte,2022-10-25,NaN,NaN,NaN,589.0
6147,CMD-Q2-03199,CLI0187,PRD0091,7,75.28,526.96,2024-05-21,livrée,CB,Nouvelle-Aquitaine,...,False,0.00,Montpellier,Île-de-France,Particulier,2020-10-24,NaN,NaN,NaN,1305.0
6148,CMD-Q2-03200,CLI0434,PRD0059,8,117.97,943.76,2024-06-25,livrée,CB,PACA,...,False,0.00,Lyon,Nouvelle-Aquitaine,Particulier,2020-06-14,Produit_Aud_59,Audio,ElecPlus,1472.0

tranche_montant
100-500€     2953
500-2000€    2170
<100€         642
>2000€        384
Name: count, dtype: int64
saison
printemps    2486
hiver        1839
été          1220
automne       604
Name: count, dtype: int64
est_annulee
False    5544
True      605
Name: count, dtype: int64

### Ex T8 ⭐⭐⭐ — Validation qualité
Écris une fonction `valider_pipeline(df) -> bool` qui :
1. Vérifie qu'il n'y a plus de NaN sur les colonnes critiques
2. Vérifie qu'il n'y a plus de doublons
3. Vérifie que tous les prix sont > 0
4. Vérifie que toutes les quantités sont > 0
5. Vérifie que montant_total == quantite × prix_unitaire (à 1 centime près)
6. Retourne True si tout est OK, False sinon avec les erreurs détaillées

In [ ]:
# TON CODE ICI

### Ex T9 ⭐⭐⭐ — Analyse métier post-transform
Maintenant que les données sont propres, répondez en code :
1. Quel est le CA total du S1 2024 ?
2. Quel trimestre a le CA le plus élevé ?
3. Quelle région génère le plus de CA ?
4. Quel segment client est le plus rentable ?
5. Quelle catégorie de produit a le taux d'annulation le plus élevé ?
6. Quel est le CA perdu sur les annulations ?

In [ ]:
# TON CODE ICI

---
# 🔵 PARTIE LOAD

### Ex L1 ⭐ — Export CSV
1. Exportez le DataFrame enrichi en CSV dans `../output/commandes_enrichies.csv`
2. Vérifiez la taille du fichier en Ko
3. Rechargez le CSV et vérifiez que le shape est identique

In [ ]:
# TON CODE ICI

### Ex L2 ⭐⭐ — Export Parquet
1. Exportez en Parquet dans `../output/commandes_S1.parquet`
2. Comparez la taille CSV vs Parquet
3. Rechargez le Parquet et vérifiez le shape
4. Mesurez le temps de lecture CSV vs Parquet avec `%%time`

In [ ]:
# TON CODE ICI

### Ex L3 ⭐⭐ — SQLite
1. Créez une base SQLite `../output/ecommerce.db`
2. Chargez le DataFrame dans une table `commandes`
3. Créez une deuxième table `reporting` avec un agrégat par trimestre et région
4. Exécutez au moins 3 requêtes SQL directement depuis Python et affichez les résultats

In [ ]:
# TON CODE ICI

### Ex L4 ⭐⭐⭐ — Parquet partitionné
Exportez le DataFrame en Parquet partitionné par `trimestre` et `region_livraison`.

Puis répondez :
- Combien de fichiers Parquet sont créés ?
- Quelle est la taille totale vs le Parquet non partitionné ?
- Quel est l'avantage du partitionnement pour PySpark ?

In [ ]:
# TON CODE ICI

---
# 🔴 PIPELINE COMPLET

### Ex P1 ⭐⭐ — Pipeline modulaire
Écris 3 fonctions séparées :
- `extract(data_dir) -> dict`
- `transform(sources: dict) -> pd.DataFrame`
- `load(df, output_dir) -> None`

Chacune doit avoir une docstring et des logs.
Teste chaque fonction indépendamment.

In [ ]:
# TON CODE ICI

### Ex P2 ⭐⭐⭐ — Pipeline avec gestion d'erreurs
Améliore ton pipeline avec :
1. `try/except` sur chaque étape critique
2. Un log d'erreur détaillé si une étape échoue
3. La pipeline ne doit pas crasher complètement si un fichier est manquant — elle doit logger l'erreur et continuer avec les autres

In [ ]:
# TON CODE ICI

### Ex P3 ⭐⭐⭐ — Tests unitaires du pipeline
Écris 5 tests pour ton pipeline :
1. `test_extract_retourne_4_sources()`
2. `test_transform_supprime_doublons()`
3. `test_transform_pas_de_prix_negatif()`
4. `test_transform_montant_coherent()`
5. `test_load_cree_les_fichiers()`

Chaque test affiche ✅ PASS ou ❌ FAIL.

In [ ]:
# TON CODE ICI

### Ex P4 ⭐⭐⭐⭐ — PROJET FINAL : Pipeline automatisé
Crée un pipeline complet qui :

1. **Détecte automatiquement** tous les fichiers CSV dans `../data_etl/` qui commencent par `commandes_`
2. **Les traite tous** sans avoir à spécifier les chemins manuellement
3. **Génère un rapport HTML** avec :
   - Les statistiques clés (CA, nb commandes, taux annulation)
   - 3 graphiques Plotly intégrés
4. **Sauvegarde** en CSV + Parquet + SQLite
5. **Loggue** chaque étape avec timestamps

C'est exactement ce que vous ferez en PySpark la semaine prochaine, mais à l'échelle de plusieurs To.

📎 Docs utiles :
- [glob — trouver des fichiers](https://docs.python.org/3/library/glob.html)
- [logging](https://docs.python.org/3/library/logging.html)
- [Plotly — export HTML](https://plotly.com/python/interactive-html-export/)

In [ ]:
# TON CODE ICI